name: Release to NPM and GitHub

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release Type"
        required: true
        type: choice
        options:
          - "major"
          - "minor"
          - "patch"
        default: "patch"

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "main"
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i

      - name: NPM Setup
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

      - name: Git Setup
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Release
        run: pnpm release.ci -- ${{ github.event.inputs.releaseType }}
        env:
          GITHUB_TOKEN: ${{ env.PUSH_TOKEN }}
